sudo: false
language: node_js
node_js:
 - '8.12'
cache:
  directories:
  - node_modules
branches:
  only:
  - master
notifications:
  email: true
jobs:
  include:
    - stage: Installing dependencies
      script: npm install
    - stage: Test code      
      script: npm run build-theme
      script: npm run eslint        
before_deploy: 
  - npm run build
deploy:
  provider: pages
  local-dir: public
  target-branch: gh-pages
  repo: front10/landing-page-book
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
env:
  global:
    - secure: "TfTnvOnHGDWNu4rrca4QeKVZrNWpGQrck6WRdupFsfRh9/+YYQ3Fypt8gCykAxe/xcHovMdifAD4ZRGj+yILEDRR7C3i0IgGJx+WIZU3xTHNRzYzSlp6bC4vXNbxd//E8F6C2cauyq8g6INJDNf33+VwmD2uTduUCKH+uB8ZEPQrCnKnoP3z8gIdq+SC/DOl2KFRpcIQNF94jImANwFvz2tNwZviZBJcVuPVwchCX40TGSzTFDwjjkSI9r3KCKhx3CrhabHU96aneVBtVWLNNPD08t9V4vPI75wkALj+UlLJcqPCiU25ywNWXPFi59CTwegZh1KU0uWuPU6OTvPzgZ5xGo2Hvy6A9x3c3kh1LHka2KeKF02V1oTGMObUy50io9QTMQuMOP1t7U3W7QI1BbmqOFWlh4vqDZ9wlljg1/cVsQhfOILZn8Ow4R4mgYVpiKwoSzOAymSSn7/6VpvNNxoF/+sIPzrJ+PQAPLjIUBeY04xgnbSaWmSsPuanXURXQ20o54VDGEzJT+EC8zroDuZSl6zaTNOK+KloKokLZa29wijHif30sjLlHj9GD3xC2YWbu7KUMll4Kwc+/gA0AaY9Aq9XlM7fnRNCKiwB8HQvJMJBQGauF8FVjpjzaqQOlQ4ExQAgz+S4rGsYPkCTVDpnqk0IJ9UBwug7blghXGE="
addons:
  browserstack:
    username: "yoandrycollazo1"
    access_key: "keqUpLHUTfApAq2fM77i"