version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/landing-page-book # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/node:8.12.0 # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands            
      - checkout # special step to check out source code to working directory         
      - restore_cache: # special step to restore the dependency cache 
          key: dependency-cache-{{ checksum "package.json" }}      
      - run:
         name: Deploy to GitHub Pages
         command: './scripts/deploy-ghpages.sh'    
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules     
      - store_artifacts:
          path: public